### ISSUE TITLE
Extract.sh fails when appvault is used on Android P image

### ISSUE THREAD

**Issue by EraserKing** [linusyang92/mipay-extract#17]
Without --appvault, everything is working perfectly, but it fails when --appvault is turned on.
For example, for this image (http://bigota.d.miui.com/8.9.20/miui_MIMIX2S_8.9.20_be2f1f2e26_9.0.zip), which is for MIX 2S / MIUI 10 8.9.20 / Android P, it throws an exception when decompiling PersonalAssistant
![image](https://user-images.githubusercontent.com/1160403/45917914-5fc47700-beb1-11e8-8736-1a2ab22d8c19.png)

As far as I see, there's no such smali file. Under "system/priv-app/PersonalAssistant/smali/com/", ONLY "sina" folder, no "miui" folder.

In #14, I saw you mentioned 8.9.7 is fine. I also tried that - it turns out, bash (under WSL) is indeed working fine, but cmd fails, seems when assembling the patched smali files.
![image](https://user-images.githubusercontent.com/1160403/45918098-4a9d1780-beb4-11e8-9d03-92251dd23666.png)
However this looks a separate issue, and I'm not sure if this is related to the 8.9.20 issue.

**Comment by linusyang92** [comment]
@EraserKing This is due to multiple DEX files existing in the APK file. Fixed in the latest script. Please try and report.

**Comment by linusyang92** [comment]
@EraserKing BTW, both screenshots indicate that you're running scripts under WSL but not using the native Batch files. Always try to use the **native BAT** files or run scripts in **native Linux VMs**.

**WSL is not recommended** due to the file system issues. JRE in WSL is a Linux version and cannot handle file locks of Windows filesystems well. Smali/Baksmali normally run concurrently on multi-cores and some thread may not be able to properly create files due to locks by other threads. The scripts may silently fail (just like your second screenshot).

**Comment by EraserKing** [comment]
Great, thanks! This time it's working: it successfully packed PersonalAssist of 8.9.20 build.

By the way, the second picture is cmd but not WSL... I also prefer the native cmd way, and WSL is only used when cmd is not working.

**Comment by linusyang** [comment]
@EraserKing It is WSL. The compact dex converter you are using is 64-bit native Linux version. It can only be executed under WSL.

If you are using CMD, the output will be different. There will be lines like "prepare flinux.exe" and the cdex converter will have a suffix `_32`.

**Comment by EraserKing** [comment]
Oops. Maybe I had bad memory.
